import { ArrowDownRight, ChevronLeft } from "lucide-react";
import { Link, useRoute } from "wouter";
import PortfolioNav from "@/components/PortfolioNav";
import ScrollReveal from "@/components/ScrollReveal";
import { getCaseStudy } from "@/data/portfolio";

// Moving Paper Gallery: concise case studies show artistic intent and process without overwhelming the image-led experience.
export default function CaseStudy() {
  const [, params] = useRoute("/cases/:slug");
  const current = getCaseStudy(params?.slug ?? "");
  if (!current) return <div className="paper-site min-h-screen"><PortfolioNav /><main className="px-4 py-24 text-center"><h1 className="juz-heading text-6xl">КЕЙС НЕ НАЙДЕН</h1><Link href="/series" className="text-link mt-8">Вернуться к сериям</Link></main></div>;
  const sections = [["Задача", current.challenge], ["Идея", current.idea], ["Подход", current.approach], ["Результат", current.result]];
  return <div className="paper-site page-transition min-h-screen overflow-x-hidden text-[#1d2547]"><PortfolioNav /><main><section className="case-hero px-4 py-14 sm:px-7 sm:py-20 lg:px-10" style={{ backgroundColor: current.color }}><div className="mx-auto grid max-w-[1540px] gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><Link href="/series" className="series-back"><ChevronLeft className="h-4 w-4" /> Все серии</Link><ScrollReveal><p className="case-category">{current.category}</p><h1 className="juz-heading text-[clamp(4rem,9vw,9.5rem)] leading-[.7] tracking-[-.085em]">{current.title}</h1></ScrollReveal></div><ScrollReveal delay={90}><div className="case-hero-image"><img src={current.image} alt={current.title} /></div></ScrollReveal></div></section><section className="case-content px-4 py-16 sm:px-7 sm:py-24 lg:px-10"><div className="mx-auto grid max-w-[1540px] gap-12 lg:grid-cols-[.7fr_1.3fr]"><ScrollReveal><aside className="case-tools"><span>Инструменты</span>{current.tools.map((tool) => <b key={tool}>{tool}</b>)}</aside></ScrollReveal><div className="case-steps">{sections.map(([title, body], index) => <ScrollReveal key={title} delay={index * 70}><article><span>0{index + 1}</span><h2 className="juz-heading">{title}</h2><p>{body}</p></article></ScrollReveal>)}</div></div></section><section className="case-mockups px-4 py-16 sm:px-7 sm:py-24 lg:px-10"><div className="mx-auto max-w-[1540px]"><ScrollReveal><p className="case-category">Применение кадра</p><h2 className="juz-heading text-[clamp(3rem,6vw,6.5rem)] leading-[.75] tracking-[-.07em]">КАДР<br />В МИРЕ</h2></ScrollReveal><div className="case-mockup-grid mt-12"><ScrollReveal><figure className="mockup-phone"><img src={current.image} alt="Работа в формате обоев телефона" /><figcaption>Обои телефона</figcaption></figure></ScrollReveal><ScrollReveal delay={70}><figure className="mockup-poster"><img src={current.image} alt="Работа в формате постера" /><figcaption>Постер</figcaption></figure></ScrollReveal><ScrollReveal delay={140}><figure className="mockup-cover"><img src={current.image} alt="Работа в формате обложки" /><figcaption>Обложка истории</figcaption></figure></ScrollReveal></div></div></section><section className="case-cta px-4 py-16 sm:px-7 sm:py-24 lg:px-10"><ScrollReveal className="mx-auto flex max-w-[1540px] flex-col justify-between gap-7 sm:flex-row sm:items-end"><h2 className="juz-heading">ХОТИТЕ<br />СВОЙ МИР</h2><Link href="/#order" className="pinterest-portal">Собрать заявку <ArrowDownRight className="h-5 w-5" /></Link></ScrollReveal></section></main></div>;
}
